meta:
  releases:
    - name:    bosh
      version: "271.0.0"
      sha1:    8d0c61e5cfaa1fc3c58a678ca700da1db8e8c567
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh?v=" meta.releases.bosh.version ))

    - name:    bpm
      version: "1.1.8"
      sha1:    c956394fce7e74f741e4ae8c256b480904ad5942
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=" meta.releases.bpm.version ))

    - name:    uaa
      version: "74.17.0"
      sha1:    ad4967615f2321648372497402ca6359ab8ba0df
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=" meta.releases.uaa.version ))

    - name:    credhub
      version: "2.6.0"
      sha1:    c45af16ed393bb3cf061b8749e3ee4cae74ce995
      url:     (( concat "https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=" meta.releases.credhub.version ))

    - name:    garden-runc
      version: "1.19.12"
      sha1:    1d2002c2d14738443e11a1fb724e941f45cdb3e7
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=" meta.releases.garden-runc.version ))

    - name:    port-forwarding
      version: "6"
      sha1:    40d0d26a217bf4f7398c1d01ffd47619349a2639
      url:     (( concat "https://github.com/cloudfoundry-community/port-forwarding-boshrelease/releases/download/v" meta.releases.port-forwarding.version "/port-forwarding-" meta.releases.port-forwarding.version ".tgz" ))

    - name:    os-conf
      version: "21.0.0"
      sha1:    7579a96515b265c6d828924bf4f5fae115798199
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=" meta.releases.os-conf.version ))

    - name:    vault-credhub-proxy
      version: "1.1.9"
      url:     (( concat "https://s3.amazonaws.com/vault-credhub-proxy-boshrelease/vault-credhub-proxy-release-" meta.releases.vault-credhub-proxy.version ".tgz" ))
      sha1:    8038e8eb63b993a4c95e96924a88e4e3e6b251e5

    - name:    node-exporter
      version: 4.2.0
      url:     (( concat "https://github.com/bosh-prometheus/node-exporter-boshrelease/releases/download/v" meta.releases.node-exporter.version "/node-exporter-" meta.releases.node-exporter.version ".tgz" ))
      sha1:    7161837435dae4bdc1a9356f7d411be3822666ea

    - name:    bosh-aws-cpi
      version: "82"
      sha1:    1a4826469e715f5595de38a15df7b7f511fbfe85
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-aws-cpi-release?v=" meta.releases.bosh-aws-cpi.version ))

    - name:    bosh-azure-cpi
      version: "37.2.0"
      sha1:    f658b25b6404a5b5676ab6379b99170f300a5124
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-azure-cpi-release?v=" meta.releases.bosh-azure-cpi.version ))

    - name:    bosh-openstack-cpi
      version: "44"
      sha1:    7c9be83eb11214db85ef5320f26ec9db8fab353f
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-openstack-cpi-release?v=" meta.releases.bosh-openstack-cpi.version ))

    - name:    bosh-google-cpi
      version: "30.0.0"
      sha1:    fe4643b66f56dfd8a58df70b647bdc7d7e0c1273
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-google-cpi-release?v=" meta.releases.bosh-google-cpi.version ))

    - name:    bosh-vsphere-cpi
      version: "53.0.9"
      sha1:    f1e9a08341229ff23ee08e85d7b6f559b9b8cdc2
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-vsphere-cpi-release?v=" meta.releases.bosh-vsphere-cpi.version ))

    - name:    bosh-warden-cpi
      version: "41"
      sha1:    b751ea458fc54f3e9f8af29ff7fa25bcd1f31f4c
      url:     (( concat "https://bosh.io/d/github.com/cppforlife/bosh-warden-cpi-release?v=" meta.releases.bosh-warden-cpi.version ))


  stemcells:
    aws:
      url:  https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=621.71
      sha1: f2b54011eb4891f86638294c9f2d8670b04e371b
    azure:
      url:  https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-xenial-go_agent?v=621.71
      sha1: 29ce83b7367c0c62065b4f7a5cd27dbccdb7b921
    google:
      url:  https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=621.71
      sha1: d6b8630e31cea498bf578113d681503553368401
    openstack:
      url:  https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-xenial-go_agent?v=621.71
      sha1: 5fa0e1b33b2411e9043e2eb3085ebe133ad2116e
    vsphere:
      url:  https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=621.71
      sha1: 0e37c4ad14cec49dcdfa227b2a374f229a695fa5
