---
params:
  subnet_addr: (( param "What network CIDR is your protobosh's network?" ))
  default_gateway: (( param "What is the gateway IP of your protobosh's network?" ))
  dns: (( param "What DNS servers should your protobosh use?" ))
  ephemeral_disk_size: 25_600
  persistent_disk_size: 32_768

meta:
  stemcells:
    aws:
      url:  https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=315.45
      sha1: 0502ba37e931193269eb75c60c408be3f249d0de
    azure:
      url:  https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-xenial-go_agent?v=315.45
      sha1: b20dca6641ab6bbf62e2265bc470ff3755c142d5
    google:
      url:  https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=315.45
      sha1: e7ba7f4e7027ee61d7e02dd106cdb67a0f6d1e0e
    openstack:
      url:  https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-xenial-go_agent?v=315.45
      sha1: 0969518f354fa3a90a1ea89375148a6d5f518e8c
    vsphere:
      url:  https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=315.45
      sha1: 457c70af10eea8ab2157a4d0f82eab242f4f0b6b

  stemcell: (( param "The IaaS-specific kit did not specify its stemcell; please file an issue with your Kit Author" ))
  mbus_bootstrap_password: (( vault meta.vault "/mbus_bootstrap:password" ))

resource_pools:
- name: (( grab params.bosh_vm_type ))
  network: (( grab params.bosh_network ))
  stemcell: (( grab meta.stemcell ))
  env:
    bosh:
      password: (( vault meta.vault "/vcap:password-crypt-sha512" ))
      mbus:
        cert: 
          ca: (( vault meta.vault "/ssl/ca:certificate" ))
          certificate: (( vault meta.vault "/ssl/mbus:certificate" ))
          private_key: (( vault meta.vault "/ssl/mbus:key" ))

disk_pools:
  - name: (( grab params.bosh_disk_pool ))
    disk_size: (( grab params.persistent_disk_size ))

networks:
- name: (( grab params.bosh_network ))
  type: manual
  subnets:
  - range:    (( grab params.subnet_addr ))
    gateway:  (( grab params.default_gateway ))
    dns:      (( grab params.dns ))
    static: [ (( grab params.static_ip )) ]

instance_groups:
- name: bosh
  vm_type:              (( prune ))
  persistent_disk_type: (( prune ))
  resource_pool:        (( grab params.bosh_vm_type ))
  persistent_disk_pool: (( grab params.bosh_disk_pool ))

cloud_provider:
  mbus: (( concat "https://mbus:" meta.mbus_bootstrap_password "@" params.static_ip ":6868" ))
  cert:
    ca: (( vault meta.vault "/ssl/ca:certificate" ))
    certificate: (( vault meta.vault "/ssl/mbus:certificate" ))
    private_key: (( vault meta.vault "/ssl/mbus:key" ))
  properties:
    ntp: (( grab params.ntp ))

    blobstore:
      provider: local
      path:     /var/vcap/micro_bosh/data/cache

    agent:
      mbus: (( concat "https://mbus:" meta.mbus_bootstrap_password "@0.0.0.0:6868" ))
