---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-go

inputs:
  - name: git-ci
  - name: git
  - name: bosh-deployment

outputs:
  - name: git

run:
  path: git-ci/ci/tasks/get-latest-bosh-deployment/task
