---
params:
  google_project: (( param "Enter the project name that your BOSH will be deployed into" ))

  ntp: # use GCP ntp
  - (( replace ))
  - time.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com

instance_groups:
- name: bosh
  jobs:
  - name: google_cpi
    release: bosh-google-cpi
  properties:
    google:
      project: (( grab params.google_project ))
      json_key: (( vault meta.vault "/google:json_key" ))
    director:
      cpi_job: google_cpi

releases:
- name:    bosh-google-cpi
  version: 29.0.1
  url:     https://bosh.io/d/github.com/cloudfoundry/bosh-google-cpi-release?v=29.0.1
  sha1:    aba0451b5be65d8bbf3cf7f289c5432192892284
