---
params:
  openstack_auth_url: (( param "What is the OpenStack Auth URL?" ))
  openstack_username: (( vault meta.vault "/openstack/creds:username" ))
  openstack_password: (( vault meta.vault "/openstack/creds:password" ))
  openstack_domain:   (( vault meta.vault "/openstack/creds:domain" ))
  openstack_project:  (( vault meta.vault "/openstack/creds:project" ))
  openstack_region:   (( param "What is the OpenStack Region?" ))
  openstack_ssh_key:  (( param "What is the OpenStack SSH Key Name?" ))
  openstack_default_security_groups: (( param "What OpenStack SGs are applied to VMs by default?" ))

instance_groups:
- name: bosh
  jobs:
  - name: openstack_cpi
    release: bosh-openstack-cpi
  properties:
    director:
      cpi_job: openstack_cpi

    openstack:
      auth_url: (( grab params.openstack_auth_url ))
      username: (( grab params.openstack_username ))
      api_key: (( grab params.openstack_password ))
      domain: (( grab params.openstack_domain ))
      project: (( grab params.openstack_project ))
      region: (( grab params.openstack_region ))
      default_key_name: (( grab params.openstack_ssh_key ))
      default_security_groups: (( grab params.openstack_default_security_groups ))
      human_readable_vm_names: true

releases:
- name:    bosh-openstack-cpi
  version: 41
  url:     https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=41
  sha1:    1d65bb6502ca4eafde3c7fee0fd584c5dfc0b35b
