---
params:
  port_forwarding_rules: []

  internal_network_prefix: 10.253 # changed from traditional 10.254 on purpose, to allow
                                  # a bosh-lite on bosh-lite

instance_groups:
- name: bosh
  jobs:
  - name: warden_cpi
    release: bosh-warden-cpi
  - name: garden
    release: garden-runc
  - name: port_forwarding
    release: port-forwarding
  - name: iptables
    release: port-forwarding
  properties:
    director:
      cpi_job: warden_cpi
    warden_cpi:
      host_ip: (( concat params.internal_network_prefix ".50.4" ))
      warden:
        connect_network: tcp
        connect_address: 127.0.0.1:7777
      actions:
        expand_stemcell_tarball: false
      agent:
        mbus: (( grab instance_groups.bosh.properties.agent.mbus ))
        blobstore:
          provider: dav
          options:
            endpoint: (( concat "http://" instance_groups.bosh.properties.blobstore.address ":" instance_groups.bosh.properties.blobstore.port ))
            user: (( grab instance_groups.bosh.properties.blobstore.agent.user ))
            password: (( grab instance_groups.bosh.properties.blobstore.agent.password ))
    garden:
      network_pool: (( concat params.internal_network_prefix ".0.0/22" ))
      listen_network: tcp
      listen_address: 127.0.0.1:7777
      disk_quota_enabled: false
      allow_host_access: true
      default_container_grace_time: 0

    port_forwarding:
      rules: (( grab params.port_forwarding_rules ))
    iptables:
      nat:
        POSTROUTING:
        - -d 10.244.0.0/16 -j MASQUERADE

releases:
- name:    bosh-warden-cpi
  version: 40
  sha1:    723b0f0c92e0be3c5068d31704fd9b383d9e515f
  url:     https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-warden-cpi-40-ubuntu-xenial-170.9-20181126-234707-455789313-20181126234713.tgz

- name:    garden-runc
  version: 1.16.3
  url:     https://s3.amazonaws.com/bosh-compiled-release-tarballs/garden-runc-1.16.3-ubuntu-xenial-170.9-20181126-235709-948256719-20181126235720.tgz
  sha1:    3ffd5f1e336fc1b8bf4457b9b97a5ccf8138997f

- name:    port-forwarding
  version: 6
  url:     https://github.com/cloudfoundry-community/port-forwarding-boshrelease/releases/download/v6/port-forwarding-6.tgz
  sha11:   40d0d26a217bf4f7398c1d01ffd47619349a2639
