---
params:
  port_forwarding_rules: []

  internal_network_prefix: 10.253 # changed from traditional 10.254 on purpose, to allow
                                  # a bosh-lite on bosh-lite

instance_groups:
- name: bosh
  jobs:
  - name: warden_cpi
    release: bosh-warden-cpi
  - name: garden
    release: garden-runc
  - name: port_forwarding
    release: port-forwarding
  - name: iptables
    release: port-forwarding
  properties:
    director:
      cpi_job: warden_cpi
    warden_cpi:
      host_ip: (( concat params.internal_network_prefix ".50.4" ))
      warden:
        connect_network: tcp
        connect_address: 127.0.0.1:7777
      actions:
        expand_stemcell_tarball: false
      agent:
        mbus: (( grab instance_groups.bosh.properties.agent.mbus ))
        blobstore:
          provider: dav
          options:
            endpoint: (( concat "http://" instance_groups.bosh.properties.blobstore.address ":" instance_groups.bosh.properties.blobstore.port ))
            user: (( grab instance_groups.bosh.properties.blobstore.agent.user ))
            password: (( grab instance_groups.bosh.properties.blobstore.agent.password ))
    garden:
      network_pool: (( concat params.internal_network_prefix ".0.0/22" ))
      listen_network: tcp
      listen_address: 127.0.0.1:7777
      disk_quota_enabled: false
      allow_host_access: true
      default_container_grace_time: 0

    port_forwarding:
      rules: (( grab params.port_forwarding_rules ))
    iptables:
      nat:
        POSTROUTING:
        - -d 10.244.0.0/16 -j MASQUERADE

releases:
- name:    bosh-warden-cpi
  version: 41
  sha1:    b751ea458fc54f3e9f8af29ff7fa25bcd1f31f4c
  url:     https://bosh.io/d/github.com/cppforlife/bosh-warden-cpi-release?v=41

- name:    garden-runc
  version: 1.18.3
  url:     https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.18.3
  sha1:    1aa15e644c6c0c6c7ec072bf668fe5d9bcc4c632

- name:    port-forwarding
  version: 6
  url:     https://github.com/cloudfoundry-community/port-forwarding-boshrelease/releases/download/v6/port-forwarding-6.tgz
  sha11:   40d0d26a217bf4f7398c1d01ffd47619349a2639
