---
exodus:
  netop_sshkey:   (( vault meta.vault "/op/net:private" ))
  sysop_password: (( vault meta.vault "/op/sys:password" ))

releases:
  - name:    os-conf
    version: 20
    url:     https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=20
    sha1:    42b1295896c1fbcd36b55bfdedfe86782b2c9fba

instance_groups:
  - name: bosh
    jobs:
      - release: os-conf
        name:    user_add

        properties:
          persistent_homes: true
          users:
            - name: netop
              public_key: (( vault meta.vault "/op/net:public" ))

            - name: sysop
              crypted_password: (( vault meta.vault "/op/sys:password-crypt-sha512" ))
