---
params:
  iaas: (( param "Please specify the IaaS that BOSH will be instrumenting (aws, vsphere, azure, openstack, ..." ))

  bosh_network: bosh
  bosh_disk_pool: bosh
  bosh_vm_type: small

  stemcell_os: ubuntu-trusty
  stemcell_version: latest

  ntp: [ 0.pool.ntp.org, 1.pool.ntp.org ]

  type: bosh # bosh or bosh-init
